from Grafo import Grafo


grafo = Grafo()

# grafo.adicionar_vertice('a')
# grafo.adicionar_vertice('b')
# grafo.adicionar_vertice('c')
# grafo.adicionar_vertice('d')

# grafo.adicionar_aresta('b', 'c', 5)
# grafo.adicionar_aresta('c', 'b', 5)
# grafo.adicionar_aresta('a', 'b', 3)
# grafo.adicionar_aresta('b', 'a', 3)
# grafo.adicionar_aresta('a', 'c', 4)
# grafo.adicionar_aresta('c', 'a', 4)
# grafo.adicionar_aresta('a', 'd', 2)
# grafo.adicionar_aresta('d', 'a', 2)

grafo.adicionar_vertice('a')
grafo.adicionar_vertice('b')
grafo.adicionar_vertice('c')
grafo.adicionar_vertice('d')
grafo.adicionar_vertice('e')
grafo.adicionar_vertice('f')
grafo.adicionar_vertice('g')
grafo.adicionar_vertice('h')

grafo.adicionar_aresta('a', 'c', 2)
grafo.adicionar_aresta('a', 'f', 2)
grafo.adicionar_aresta('b', 'c', 2)
grafo.adicionar_aresta('c', 'd', 2)
grafo.adicionar_aresta('c', 'e', 2)
grafo.adicionar_aresta('c', 'h', 2)
grafo.adicionar_aresta('f', 'e', 2)
grafo.adicionar_aresta('g', 'f', 2)
grafo.adicionar_aresta('g', 'h', 2)

print(grafo)
print()
# print(grafo.get_adjacentes('a'))
# print(grafo.obter_grau('a'))
# print(grafo.eh_regular())
# print(grafo.eh_completo())
# print(grafo.eh_conexo())
# print(grafo.eh_completo_v2())
# grafo.dijkstra('b', 'a')

print(grafo.prim('a'))
print(grafo.ordenacao_topologica())
